<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/acfunAd.proto

/**
 * Protobuf enum <code>AdType</code>
 */
class AdType
{
    /**
     * <pre>
     *安卓启动闪屏1620*2432(2轮播随机展示)
     * </pre>
     *
     * <code>ACFUN_ANDROID_SPLASH = 0;</code>
     */
    const ACFUN_ANDROID_SPLASH = 0;
    /**
     * <pre>
     *ios启动闪频1125*1719(2轮播图随机展示)
     * </pre>
     *
     * <code>ACFUN_IOS_SPLASH = 1;</code>
     */
    const ACFUN_IOS_SPLASH = 1;
    /**
     * <pre>
     *1125*435
     * </pre>
     *
     * <code>ACFUN_CAROUSEL_FIGURE = 2;</code>
     */
    const ACFUN_CAROUSEL_FIGURE = 2;
    /**
     * <pre>
     *1035*240
     * </pre>
     *
     * <code>ACFUN_EACH_PARTITION = 3;</code>
     */
    const ACFUN_EACH_PARTITION = 3;
    /**
     * <pre>
     *504*282
     * </pre>
     *
     * <code>ACFUN_OTHER_REGION = 4;</code>
     */
    const ACFUN_OTHER_REGION = 4;
    /**
     * <pre>
     *1035*390
     * </pre>
     *
     * <code>ACFUN_SEARCH = 5;</code>
     */
    const ACFUN_SEARCH = 5;
}

