<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/acfunAd.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>App</code>
 */
class App extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * <code>string domain = 3;</code>
     */
    private $domain = '';
    /**
     * <code>string ver = 4;</code>
     */
    private $ver = '';
    /**
     * <code>string bundle = 5;</code>
     */
    private $bundle = '';
    /**
     * <code>uint32 privacypolicy = 6;</code>
     */
    private $privacypolicy = 0;
    /**
     * <code>uint32 paid = 7;</code>
     */
    private $paid = 0;

    public function __construct() {
        \GPBMetadata\Proto\AcfunAd::initOnce();
        parent::__construct();
    }

    /**
     * <code>string id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 2;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>string domain = 3;</code>
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * <code>string domain = 3;</code>
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain = $var;
    }

    /**
     * <code>string ver = 4;</code>
     */
    public function getVer()
    {
        return $this->ver;
    }

    /**
     * <code>string ver = 4;</code>
     */
    public function setVer($var)
    {
        GPBUtil::checkString($var, True);
        $this->ver = $var;
    }

    /**
     * <code>string bundle = 5;</code>
     */
    public function getBundle()
    {
        return $this->bundle;
    }

    /**
     * <code>string bundle = 5;</code>
     */
    public function setBundle($var)
    {
        GPBUtil::checkString($var, True);
        $this->bundle = $var;
    }

    /**
     * <code>uint32 privacypolicy = 6;</code>
     */
    public function getPrivacypolicy()
    {
        return $this->privacypolicy;
    }

    /**
     * <code>uint32 privacypolicy = 6;</code>
     */
    public function setPrivacypolicy($var)
    {
        GPBUtil::checkUint32($var);
        $this->privacypolicy = $var;
    }

    /**
     * <code>uint32 paid = 7;</code>
     */
    public function getPaid()
    {
        return $this->paid;
    }

    /**
     * <code>uint32 paid = 7;</code>
     */
    public function setPaid($var)
    {
        GPBUtil::checkUint32($var);
        $this->paid = $var;
    }

}

