<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/DEMOAd.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Bid</code>
 */
class Bid extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * <code>string imp_id = 2;</code>
     */
    private $imp_id = '';
    /**
     * <code>uint32 price = 3;</code>
     */
    private $price = 0;
    /**
     * <code>uint64 adid = 4;</code>
     */
    private $adid = 0;
    /**
     * <code>.MaterialMeta material = 5;</code>
     */
    private $material = null;

    public function __construct() {
        \GPBMetadata\Proto\DEMOAd::initOnce();
        parent::__construct();
    }

    /**
     * <code>string id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <code>string imp_id = 2;</code>
     */
    public function getImpId()
    {
        return $this->imp_id;
    }

    /**
     * <code>string imp_id = 2;</code>
     */
    public function setImpId($var)
    {
        GPBUtil::checkString($var, True);
        $this->imp_id = $var;
    }

    /**
     * <code>uint32 price = 3;</code>
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * <code>uint32 price = 3;</code>
     */
    public function setPrice($var)
    {
        GPBUtil::checkUint32($var);
        $this->price = $var;
    }

    /**
     * <code>uint64 adid = 4;</code>
     */
    public function getAdid()
    {
        return $this->adid;
    }

    /**
     * <code>uint64 adid = 4;</code>
     */
    public function setAdid($var)
    {
        GPBUtil::checkUint64($var);
        $this->adid = $var;
    }

    /**
     * <code>.MaterialMeta material = 5;</code>
     */
    public function getMaterial()
    {
        return $this->material;
    }

    /**
     * <code>.MaterialMeta material = 5;</code>
     */
    public function setMaterial(&$var)
    {
        GPBUtil::checkMessage($var, \MaterialMeta::class);
        $this->material = $var;
    }

}

