<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/acfunAd.proto

/**
 * Protobuf enum <code>Device.ConnectionType</code>
 */
class Device_ConnectionType
{
    /**
     * <code>Honeycomb = 0;</code>
     */
    const Honeycomb = 0;
    /**
     * <code>WIFI = 1;</code>
     */
    const WIFI = 1;
    /**
     * <code>UNKNOWN = 2;</code>
     */
    const UNKNOWN = 2;
    /**
     * <code>NT_2G = 3;</code>
     */
    const NT_2G = 3;
    /**
     * <code>NT_4G = 4;</code>
     */
    const NT_4G = 4;
}

