<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/acfunAd.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>SeatBid</code>
 */
class SeatBid extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .Bid bid = 1;</code>
     */
    private $bid;
    /**
     * <pre>
     * 广告来源dsp识别
     * </pre>
     *
     * <code>string seat = 2;</code>
     */
    private $seat = '';

    public function __construct() {
        \GPBMetadata\Proto\AcfunAd::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .Bid bid = 1;</code>
     */
    public function getBid()
    {
        return $this->bid;
    }

    /**
     * <code>repeated .Bid bid = 1;</code>
     */
    public function setBid(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Bid::class);
        $this->bid = $arr;
    }

    /**
     * <pre>
     * 广告来源dsp识别
     * </pre>
     *
     * <code>string seat = 2;</code>
     */
    public function getSeat()
    {
        return $this->seat;
    }

    /**
     * <pre>
     * 广告来源dsp识别
     * </pre>
     *
     * <code>string seat = 2;</code>
     */
    public function setSeat($var)
    {
        GPBUtil::checkString($var, True);
        $this->seat = $var;
    }

}

