<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/acfunAd.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>BidRequest</code>
 */
class BidRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string request_id = 1;</code>
     */
    private $request_id = '';
    /**
     * <code>string api_version = 2;</code>
     */
    private $api_version = '';
    /**
     * <code>.Imp imp = 3;</code>
     */
    private $imp = null;
    /**
     * <code>.Device device = 4;</code>
     */
    private $device = null;
    /**
     * <code>.User user = 5;</code>
     */
    private $user = null;
    /**
     * <code>.App app = 6;</code>
     */
    private $app = null;

    public function __construct() {
        App\AdGenerate\GPBMetadata\Proto\AcfunAd::initOnce();
        parent::__construct();
    }

    /**
     * <code>string request_id = 1;</code>
     */
    public function getRequestId()
    {
        return $this->request_id;
    }

    /**
     * <code>string request_id = 1;</code>
     */
    public function setRequestId($var)
    {
        GPBUtil::checkString($var, True);
        $this->request_id = $var;
    }

    /**
     * <code>string api_version = 2;</code>
     */
    public function getApiVersion()
    {
        return $this->api_version;
    }

    /**
     * <code>string api_version = 2;</code>
     */
    public function setApiVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->api_version = $var;
    }

    /**
     * <code>.Imp imp = 3;</code>
     */
    public function getImp()
    {
        return $this->imp;
    }

    /**
     * <code>.Imp imp = 3;</code>
     */
    public function setImp(&$var)
    {
        GPBUtil::checkMessage($var, \Imp::class);
        $this->imp = $var;
    }

    /**
     * <code>.Device device = 4;</code>
     */
    public function getDevice()
    {
        return $this->device;
    }

    /**
     * <code>.Device device = 4;</code>
     */
    public function setDevice(&$var)
    {
        GPBUtil::checkMessage($var, \Device::class);
        $this->device = $var;
    }

    /**
     * <code>.User user = 5;</code>
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * <code>.User user = 5;</code>
     */
    public function setUser(&$var)
    {
        GPBUtil::checkMessage($var, \User::class);
        $this->user = $var;
    }

    /**
     * <code>.App app = 6;</code>
     */
    public function getApp()
    {
        return $this->app;
    }

    /**
     * <code>.App app = 6;</code>
     */
    public function setApp(&$var)
    {
        GPBUtil::checkMessage($var, \App::class);
        $this->app = $var;
    }

}

