<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/acfunAd.proto

/**
 * Protobuf enum <code>Device.DeviceType</code>
 */
class Device_DeviceType
{
    /**
     * <code>PHONE = 0;</code>
     */
    const PHONE = 0;
    /**
     * <code>TABLET = 1;</code>
     */
    const TABLET = 1;
}

