<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/acfunAd.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Geo</code>
 */
class Geo extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>double lat = 1;</code>
     */
    private $lat = 0.0;
    /**
     * <code>double lon = 2;</code>
     */
    private $lon = 0.0;
    /**
     * <code>string country = 3;</code>
     */
    private $country = '';
    /**
     * <code>string region = 4;</code>
     */
    private $region = '';
    /**
     * <code>string city = 5;</code>
     */
    private $city = '';
    /**
     * <code>string type = 6;</code>
     */
    private $type = '';

    public function __construct() {
        App\AdGenerate\GPBMetadata\Proto\AcfunAd::initOnce();
        parent::__construct();
    }

    /**
     * <code>double lat = 1;</code>
     */
    public function getLat()
    {
        return $this->lat;
    }

    /**
     * <code>double lat = 1;</code>
     */
    public function setLat($var)
    {
        GPBUtil::checkDouble($var);
        $this->lat = $var;
    }

    /**
     * <code>double lon = 2;</code>
     */
    public function getLon()
    {
        return $this->lon;
    }

    /**
     * <code>double lon = 2;</code>
     */
    public function setLon($var)
    {
        GPBUtil::checkDouble($var);
        $this->lon = $var;
    }

    /**
     * <code>string country = 3;</code>
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * <code>string country = 3;</code>
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;
    }

    /**
     * <code>string region = 4;</code>
     */
    public function getRegion()
    {
        return $this->region;
    }

    /**
     * <code>string region = 4;</code>
     */
    public function setRegion($var)
    {
        GPBUtil::checkString($var, True);
        $this->region = $var;
    }

    /**
     * <code>string city = 5;</code>
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * <code>string city = 5;</code>
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;
    }

    /**
     * <code>string type = 6;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <code>string type = 6;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, True);
        $this->type = $var;
    }

}

