<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/DEMOAd.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>MaterialMeta.AndroidApp</code>
 */
class MaterialMeta_AndroidApp extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string app_name = 1;</code>
     */
    private $app_name = '';
    /**
     * <code>string download_url = 2;</code>
     */
    private $download_url = '';

    public function __construct() {
        App\AdGenerate\GPBMetadata\Proto\DEMOAd::initOnce();
        parent::__construct();
    }

    /**
     * <code>string app_name = 1;</code>
     */
    public function getAppName()
    {
        return $this->app_name;
    }

    /**
     * <code>string app_name = 1;</code>
     */
    public function setAppName($var)
    {
        GPBUtil::checkString($var, True);
        $this->app_name = $var;
    }

    /**
     * <code>string download_url = 2;</code>
     */
    public function getDownloadUrl()
    {
        return $this->download_url;
    }

    /**
     * <code>string download_url = 2;</code>
     */
    public function setDownloadUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->download_url = $var;
    }

}

