<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/DEMOAd.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * <code>string buyer_id = 2;</code>
     */
    private $buyer_id = '';
    /**
     * <code>string yob = 3;</code>
     */
    private $yob = '';
    /**
     * <code>string keywords = 4;</code>
     */
    private $keywords = '';
    /**
     * <code>string geo = 5;</code>
     */
    private $geo = '';
    /**
     * <code>string gender = 6;</code>
     */
    private $gender = '';

    public function __construct() {
        App\AdGenerate\GPBMetadata\Proto\DEMOAd::initOnce();
        parent::__construct();
    }

    /**
     * <code>string id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <code>string buyer_id = 2;</code>
     */
    public function getBuyerId()
    {
        return $this->buyer_id;
    }

    /**
     * <code>string buyer_id = 2;</code>
     */
    public function setBuyerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->buyer_id = $var;
    }

    /**
     * <code>string yob = 3;</code>
     */
    public function getYob()
    {
        return $this->yob;
    }

    /**
     * <code>string yob = 3;</code>
     */
    public function setYob($var)
    {
        GPBUtil::checkString($var, True);
        $this->yob = $var;
    }

    /**
     * <code>string keywords = 4;</code>
     */
    public function getKeywords()
    {
        return $this->keywords;
    }

    /**
     * <code>string keywords = 4;</code>
     */
    public function setKeywords($var)
    {
        GPBUtil::checkString($var, True);
        $this->keywords = $var;
    }

    /**
     * <code>string geo = 5;</code>
     */
    public function getGeo()
    {
        return $this->geo;
    }

    /**
     * <code>string geo = 5;</code>
     */
    public function setGeo($var)
    {
        GPBUtil::checkString($var, True);
        $this->geo = $var;
    }

    /**
     * <code>string gender = 6;</code>
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * <code>string gender = 6;</code>
     */
    public function setGender($var)
    {
        GPBUtil::checkString($var, True);
        $this->gender = $var;
    }

}

